version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    hostname: dynamodb-local
    restart: always
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
